### ISSUE TITLE
Epic React has a "render while you fetch" that isn't included in the example schedule

### ISSUE THREAD

**Issue by jasikpark** [kentcdodds/kcd-learning-clubs-ideas#9]
https://github.com/kentcdodds/kcd-learning-clubs-ideas/blob/main/templates/epicreact-dev.txt contains the React Suspense section at the end of the course, but there's no mention of the "render while you fetch" section of the "build a react app" bit.

It's a little wonky then since the "build a react app" has "render while you fetch" before testing, but the schedule / the workshops do testing then suspense.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/10626596/179733494-f3f4c4cd-7d99-4849-8a35-9a6f0e9ebf2c.png">

At the very least it'd be nice to add a spot for the render while you fetch section to the schedule

I think personally I'll follow the pattern of workshop bit then building w/ it in the epic react app. So I'll do testing w/in the epic react app and then react suspense workshop and then the fetch while you render in the epic react app

**Comment by kentcdodds** [comment]
You're right. "Render as You Fetch" is a performance optimization so I think it makes sense to have it right after the performance workshop so we'll put it there. Thanks!

**Comment by jasikpark** [comment]
thanks!

**Comment by jasikpark** [comment]
oh, does it not depend on knowledge about react suspense then?

**Comment by jasikpark** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/10626596/179995079-7c0a02fc-40c0-401b-ae7d-1f922d7e03ce.png">
see "render as you fetch" mentioned in the react suspense section rather than perf 🤷

**Comment by kentcdodds** [comment]
It sort of does, not not directly negative we're not actually using suspense features in the bookshelf app. So the suspense workshop really is just a bonus, so I want to keep it at the end of the schedule.

**Comment by jasikpark** [comment]
Ah, ok! Fair
